###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [ ]:
import numpy as np
import random
import math

In [ ]:
def get_state():
    N = random.choice([3,4,5])
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    random.shuffle(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [ ]:
s = get_state()

[[5 2 6]
 [3 7 1]
 [4 8 0]]


In [ ]:
def get_dim(s):
  return int(math.sqrt(len(s)))

In [ ]:
s = get_state()
print(s)
print('Dimension:', get_dim(s))

[[13 20 11 23  3]
 [12 24 10  5  7]
 [19  2 21  8  9]
 [ 0 15 14 16 17]
 [ 4 18  6 22  1]]
[13, 20, 11, 23, 3, 12, 24, 10, 5, 7, 19, 2, 21, 8, 9, 0, 15, 14, 16, 17, 4, 18, 6, 22, 1]
Dimension: 5


# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [ ]:
def get_invCount(s):
    count = 0
    for i in range(len(s)):
        for j in range(i+1,len(s)):
            if s[j]!=0 and s[i] > s[j]: count += 1
    return count

In [ ]:
s = get_state()
print(s)
print(get_invCount(s))

[[12 18  8  6  3]
 [ 5 19 11  0  1]
 [24  9 10 21 14]
 [ 2 22 16  4 13]
 [15 23  7 20 17]]
[12, 18, 8, 6, 3, 5, 19, 11, 0, 1, 24, 9, 10, 21, 14, 2, 22, 16, 4, 13, 15, 23, 7, 20, 17]
112


In [ ]:
s.index(0)

8

# **Find blank row**

In [ ]:
# find row position of the blank tile
def get_blank_row(s):
  # define here
 n = int(len(s) ** 0.5)
 for i in range(len(s)):
  if s[i] == 0:
    return n-(i//n)
print(get_blank_row(s))



4


# Solvability Rules

In [ ]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not

def isSolvable(state):
  N = get_dim(state)
  I = get_invCount(state)
  R = get_blank_row(state)
  # decide solvability
  # check rules
  def isSolvable(state):
    N = get_dim(state)
    I = get_invCount(state)
    R = get_blank_row(state)

    # If N is odd, the puzzle is solvable if I is even.
    if N % 2 != 0:
        return I % 2 == 0
    else:
        if R % 2 == 0:
            return I % 2 != 0
        else:
            return I % 2 == 0

# Example usage
state = get_state()  # Generate or define a state
print(f"State: {state}")
print(f"Solvability: {isSolvable(state)}")



[[ 3 22  1 19 20]
 [14 12  8  6 13]
 [ 0 11  2  7  5]
 [ 4 21 17 16 18]
 [ 9 24 15 23 10]]
State: [3, 22, 1, 19, 20, 14, 12, 8, 6, 13, 0, 11, 2, 7, 5, 4, 21, 17, 16, 18, 9, 24, 15, 23, 10]
Solvability: None


In [ ]:
s = get_state()
isSolvable(s)


[[ 7  6  1 13]
 [15  8  2  9]
 [ 0 10 11  3]
 [ 5 14  4 12]]


In [ ]:
s = get_state()
while(isSolvable(s)==False):
  s = get_state()
print(s)


[[1 2 3]
 [5 4 6]
 [0 8 7]]
[1, 2, 3, 5, 4, 6, 0, 8, 7]
